ARG ELIXIR_VERSION=1.18.2
ARG OTP_VERSION=27.2
ARG ALPINE_VERSION=3.21.7

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-alpine-${ALPINE_VERSION}"
ARG RUNNER_IMAGE="alpine:${ALPINE_VERSION}"

FROM ${BUILDER_IMAGE} as builder

RUN apk add --no-cache build-base git curl nodejs npm

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

ENV MIX_ENV="prod"

COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY priv priv

COPY assets/package*.json assets/
RUN if [ -f assets/package.json ]; then \
      if [ -f assets/package-lock.json ]; then \
        npm --prefix ./assets ci --progress=false --no-audit --loglevel=error; \
      else \
        npm --prefix ./assets install --progress=false --no-audit --loglevel=error; \
      fi; \
    fi

COPY assets assets
COPY lib lib

RUN mix compile
RUN mix assets.deploy

COPY config/runtime.exs config/
RUN mix release

FROM ${RUNNER_IMAGE}

RUN apk add --no-cache libstdc++ openssl ncurses-libs

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

WORKDIR "/app"
RUN chown nobody /app

ENV MIX_ENV="prod"

COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/APP_NAME ./

USER nobody

CMD ["/app/bin/APP_NAME", "start"]
